### ISSUE TITLE
Very slow performance and frequent crashes with large image library

### ISSUE THREAD

**Issue by gwhobbs** [dennispassway/sanity-plugin-media-library#29]
Loading and browsing performance both slow to a crawl (~1m to load and ~1fps scrolling) and crashes are frequent when using with a library containing a few thousand images. Scrolling improves significantly when a filter is used, but due to the long initial load time and frequent crashes, this plugin becomes almost unusable. 

I plan to investigate possible performance fixes. Has anyone else observed or made any headway on similar performance issues?

**Comment by Aratramba** [comment]
Hi Grant, thanks for reporting. I can imagine this is an issue with a lot of images. We haven't really done any optimisations concerning performance. We also don't have too much time to fix things, so you might want to consider using the [other (and more official) media browser plugin](https://www.sanity.io/plugins/sanity-plugin-media), since that has "Virtualized grid + tabular views for super speedy browsing, even with thousands of assets".

**Comment by gwhobbs** [comment]
@Aratramba Thanks for linking to that! I was not aware of the other plugin. It looks like it will do what I need.
